// TODO create an assets folder to prevent push assets to public folder
import Script from 'next/script';
import './global.css';
import "@code-hike/mdx/dist/index.css"

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
  icons:{
    icon:'/images/logo.svg'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        {children}
        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        ></Script>
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        ></Script>
      </body>
    </html>
  );
}
