export const HOME_ROUTE = '/'
export const BLOG_ROUTE = '/blog'
export const SINGLE_BLOG_ROUTE = BLOG_ROUTE + '/:slug'
export const CONtACT_ME_ROUTE = '/contact-me'
export const PROJECTS_ROUTE = '/projects'
export const SINGLE_PROJECTS_ROUTE = PROJECTS_ROUTE + '/:slug'
export const RESUME_ROUTE = '/resume'