import Providers from '../../libs/providers';
import { Navbar, Sidebar } from '../../libs/components';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Providers>
      <main>
        <Sidebar />
        <div className="main-content">
          <Navbar />
          {children}
        </div>
      </main>
    </Providers>
  );
};
export default Layout;
