import Image from 'next/image';
import Sidebar from './components/sidebar';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main>
      <Sidebar />
      <div className="main-content">{children}</div>
    </main>
  );
};
export default Layout;
