import { Navbar, Sidebar } from '../../libs/components';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main>
      <Sidebar />
      <div className="main-content">
        <Navbar />
        {children}
      </div>
    </main>
  );
};
export default Layout;
