// locals
import "./global.css"

export const metadata = {
  title: "Welcome to web",
  description: "Generated by create-nx-workspace",
  icons: {
    icon: "/images/logo.svg",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  )
}
