FROM node:16-alpine
RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
WORKDIR /app
ADD package.json .
ADD package-lock.json .
RUN npm install --legacy-peer-deps
ADD . .
RUN npx nx run web:build --prod
WORKDIR /app/dist/apps/web
CMD ["npm","start"]

